Use latest (stable) tag instead of edge
Edge is now causing fatal build exception:

```console
RUN apk -U upgrade && apk add --no-cache ...
fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
Upgrading critical system libraries and apk-tools:
(1/8) Purging ssl_client (1.33.1-r4)
(2/8) Installing libcrypto3 (3.0.0-r0)
(3/8) Installing libssl3 (3.0.0-r0)
(4/8) Upgrading apk-tools (2.12.7-r0 -> 2.12.7-r1)
(5/8) Purging libretls (3.3.3p1-r0)
(6/8) Purging ca-certificates-bundle (20191127-r5)
(7/8) Purging libssl1.1 (1.1.1k-r1)
(8/8) Purging libcrypto1.1 (1.1.1k-r1)
Executing busybox-1.33.1-r4.trigger
Continuing the upgrade transaction with new apk-tools
(1/3) Upgrading musl (1.2.2-r5 -> 1.2.2-r6)
48FB1F0A2D7F0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1882
ERROR: musl-1.2.2-r6: Permission denied
(2/3) Upgrading busybox (1.33.1-r4 -> 1.34.0-r3)
48FB1F0A2D7F0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1882
ERROR: busybox-1.34.0-r3: Permission denied
(3/3) Upgrading musl-utils (1.2.2-r5 -> 1.2.2-r6)
48FB1F0A2D7F0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1882
ERROR: musl-utils-1.2.2-r6: Permission denied
3 errors; 7 MiB in 11 packages
```